
version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zuyoze33
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/CustomerOrderDb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=zuyoze33
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zuyoze33
      - POSTGRES_DB=CustomerOrderDb
    ports:
      - "5432:5432"